TeamLolyPoly/KGAMeta8th_ContractProject_DM

Assets/Main/Scenes/Devs/Dev_Ryu/GridManager.cs
Assets/Main/Scenes/Devs/Dev_Ryu/NoteSpawner.cs
Assets/Main/Scripts/Enums/GameEnum.cs
Assets/Main/Scripts/Objects/LeftNote.cs
Assets/Main/Scripts/Objects/Note.cs
Assets/Main/Scripts/Objects/RightNote.cs

[body]
- 그리드를 반전하여 왼쪽 오른쪽 구분 함

[fix] 그리드 반전

---

Assets/Main/Scripts/Objects/LeftNote.cs
Assets/Main/Scripts/Objects/Note.cs
Assets/Main/Scripts/Objects/RightNote.cs

[refactor] Note상속관계 정리

---

Assets/Main/Scenes/Devs/Dev_Ryu/BPMTest.cs
Assets/Main/Scenes/Devs/Dev_Ryu/BPMTest.cs.meta
Assets/Main/Scenes/Devs/Dev_Ryu/GridManager.cs

[body]
- BPM속도 체크 스크립트 추가
- 그리드 반전 하여 정상화

[feat] BPM , 그리드반전

---

Assets/Main/Scripts/Tests/RightGrid.cs
Assets/Main/Scripts/Tests/RightGridManager.cs
Assets/Main/Scripts/Tests/RightLongNoteSpawner.cs

[fix] 그리드 오류 수정

---

Assets/Main/Prefabs/RhythmRailVTest.prefab
Assets/Main/Prefabs/RhythmRailVTest.prefab.meta
Assets/Main/Scenes/Devs/Dev_Ryu/Edit_SampleScene.unity
Assets/Main/Scenes/Devs/Dev_Ryu/Edit_SampleScene.unity.meta
Assets/Main/Scenes/Devs/Dev_Ryu/New Material.mat
Assets/Main/Scenes/Devs/Dev_Ryu/New Material.mat.meta
Assets/Main/Scenes/Devs/Dev_Ryu/Ryu_Scene.unity
Assets/Main/Scripts/Tests/RhythmRailVisualizer.cs
Assets/Main/Scripts/Tests/RhythmRailVisualizer.cs.meta
Packages/packages-lock.json

[body]
- prefab추가 및 색깔별(빨강,노랑,파랑) prefab 생성

[feat] snare drum prefab 추가

---

Assets/Main/Scenes/Devs/Dev_Ryu/Ryu_Scene.unity
Assets/Main/Scripts/Tests/ArcToArcLongNoteSpawner.cs

[feat] 롱노트 대칭 추가

---

Assets/Main/Scripts/Objects/Note.cs

[feat] note 기울기 확정부분 구현하였습니다.

---

Assets/Main/Scenes/Devs/Dev_Ryu/Ryu_Scene.unity
Assets/Main/Scripts/Enums/GameEnum.cs
Assets/Main/Scripts/Objects/Note.cs
Assets/Main/Scripts/System/Data/GameData.cs
Assets/Main/Scripts/System/Manager/NoteGameManager.cs
Assets/Main/Scripts/Tests/CombinedSpawnManager.cs
Packages/manifest.json
Packages/packages-lock.json

[body]
- GameEnum NoteBaseType 추가
- NoteData에서 //기본 노트 타입은 숏으로 설정
- NoteGameManager에서 노트 타입 결정
- CombinedSpawnManager 노트 타입 설정을 NoteGameManager에서 가져옴
- CombinedSpawnManager에 SpawnArcSegments코루틴에 초기화 추가

[feat] 데이터 클래스 합치기 초안

---

Assets/Main/Scripts/System/Data/GameData.cs

[feat] 롱노트 정렬화

---

Assets/Main/Scripts/System/Pool/NoteRPC.cs
Assets/Main/Scripts/System/Pool/NoteRPC.cs.meta
Assets/Main/Scripts/System/Pool/PoolManager.cs
Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset

[Body]
- photon RPC로 노트 위치 동기화 코드 구현

[feat] note 포톤뷰 위치 동기화

---

Assets/Main/Scripts/Tests/BPMTest.cs

[feat] 개인 씬 수정

---

Assets/Main/Scenes/Devs/StageTest.unity
Assets/Main/Scripts/Stage/Objects/Unit/Band.cs
Assets/Main/Scripts/Stage/Objects/Unit/Unit.cs
Assets/Main/Scripts/System/Manager/Stage/AnimationSystem.cs
Assets/Main/Scripts/System/Manager/Stage/ScoreSystem.cs

[body]
- Band 유닛 애니메이션 초기화 방법 수정

[refector] Band 유닛 애니메이션 초기화 방식 수정

---

Assets/Main/Prefabs/Map/Map v2.prefab
Assets/Main/Prefabs/Map/Map v2.prefab.meta
Assets/Main/Scenes/Devs/Dev_Choi/RuntimeTest.unity
Assets/Main/Scripts/Test/CustomGrandstandCreator.cs.meta
Assets/Main/Scripts/Test/Editor.meta
Assets/Main/Scripts/Test/Editor/CustomGrandstandCreatorEditor.cs.meta

[feat] 맵 구성 배치 초안

---

Assets/Main/Scripts/System/Data/GameData.cs

[feat] 롱노트 카운트 변경

---

Assets/Main/Scripts/Stage/Objects/Unit/Unit.cs
Assets/Main/Scripts/System/Stage/AnimationSystem.cs
Assets/Main/Scripts/System/Stage/ScoreSystem.cs
Assets/Main/Textures/UI/UI_Texture_GameLogo.png.meta
Assets/Main/Textures/UI/UI_Texture_MultiModeIcon.jpg.meta
Assets/Main/Textures/UI/UI_Texture_SingleModeIcon.jpg.meta

[body]
- AnimationSystem 밴드 애니메이션 수정 방식 수정
- ScoreSystem 클래스 CleanUp 메서드 구현
- AnimationSystem 클래스 CleanUp 메서드 구현 [Todo]
@애니메이션
- (issue) ScoreSystem,AnimationSystem 클래스 CleanUp 메서드 구현

[feat] AnimationSystem 밴드 애니메이션 수정방식 수정

---

Assets/Resources/Prefabs/UI/Panels/Stage/UI_Panel_Multi_Room.prefab
Assets/Resources/Prefabs/UI/Panels/Stage/UI_Panel_Option.prefab
Assets/Resources/Prefabs/UI/Panels/Stage/UI_Panel_Single_Result.prefab

[body]
-패널 3개 머퍼리얼에 UI Mat 설정 하였습니다.

[feat] 옵션, 싱글결과,멀티룸 패널 이미지 머터리얼 설정완료

---

Assets/Main/Scenes/Devs/Dev_Choi/SyncTest.cs

[fix] 멀티 동기화 재수정

---

Assets/Main/Scenes/Devs/Dev_Beom/SpawnTest.cs
Assets/Main/Scenes/Devs/Dev_Choi/SyncTest.cs

[test] 멀티 동기화 테스트

---

Assets/Main/Scripts/Stage/Objects/Unit/Band.cs
Assets/Main/Scripts/Stage/Objects/Unit/Unit.cs
Assets/Main/Scripts/System/Manager/Stage/GameManager.cs
Assets/Main/Scripts/System/Stage/AnimationSystem.cs
Assets/Main/Scripts/System/Stage/ScoreSystem.cs

[fix] Unit AnimationSystem bug fix

---

Assets/Main/Materials/Stage/Objects/Spectator/Bands.mat
Assets/Main/Materials/Stage/Objects/Spectator/Bands.mat.meta
Assets/Main/Prefabs/Objects/Unit/MultiBandSpecter.prefab
Assets/Main/Prefabs/Objects/Unit/MultiBandSpecter.prefab.meta
Assets/Main/Prefabs/Objects/Unit/SingleBandSpecter.prefab
Assets/Main/Prefabs/Objects/Unit/SingleBandSpecter.prefab.meta

[body]
- 관중 및 밴드 스프라이트 업데이트 및 쉐이더 적용

[feat] 관중 및 밴드 스프라이트

---

Assets/Main/Materials/Stage/Objects/Spectator/Bands.mat
Assets/Main/Materials/Stage/Objects/Spectator/New Material 1.mat
Assets/Main/Materials/Stage/Objects/Spectator/New Material 2.mat
Assets/Main/Prefabs/Objects/Unit/Spectator/Bandsimage.png.meta
Assets/Main/Prefabs/Objects/Unit/Spectator/SpectatorImage.prefab
Assets/Main/Scenes/Main/Game/Main_MultiStage.unity
Assets/Main/Scenes/Main/Game/Main_SingleStage.unity

[feat] 관중 이미지 추가
